# Site settings
title: "Chris Tack Resume"
description: "Resume for Full Stack Developer Chris Tack built with Jekyll and hosted on GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Chris Tack"
resume_title:                   "Full Stack Developer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "chris_tack@mac.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "(989) 326-1488"
resume_contact_address:         "202 Madison St, Everett, WA"

resume_header_contact_info:     "202 Madison St, Everett, WA<br>(989) 326-1488 • chris_tack@mac.com"
display_header_contact_info:    "true"

resume_header_intro: "<p>Fun Facts...
<ul>
  <li>I worked as a commercial photographer for over a decade.</li>
  <li>I learned HTML, CSS, and JavaScript originally in college & returned to development in 2018</li>
  <li>I spent all of 2018 reacquainting myself with what's new in HTML5, CSS3, JavaScript and much more (self-taught and via attending a 12-week, 40hr / week course).</li>
  <li>March through July 2019 was spent as a Full Stack Developer at Zulily (where I worked from 2013 - 2020) and am looking for a full-time developer job.</li>
</ul></p>"

# <a href="http://zulily.com" target="_blank">Zulily</a>

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
resume_section_interests:       false

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/tackc/"
  # resume_twitter_url:           "http://twitter.com/tackc"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/christophertack"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://christack.com"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
